version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: Microsoft.AspNetCore.Http.Features
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Mapster
    versions:
    - 7.1.3
    - 7.1.5
  - dependency-name: Microsoft.NETCore.Platforms
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: YoutubeExplode
    versions:
    - 5.1.9
  - dependency-name: Microsoft.Extensions.Primitives
    versions:
    - 5.0.0
