////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using System;
using System.Threading.Tasks;

namespace OpenNos.Handler.CommandPackets.Inventory
{
    [PacketHeader("$Clear", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ClearInventoryPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public InventoryType InventoryType { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 3)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }

                ClearInventoryPacket packetDefinition = new ClearInventoryPacket();
                if (Enum.TryParse(packetSplit[2], out InventoryType type))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.InventoryType = type;
                }

                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(ClearInventoryPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Clear INVENTORYTYPE";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[Clear]InventoryType: {InventoryType}");

                Parallel.ForEach(session.Character.Inventory.Where(s => s.Type == InventoryType),
                    inv =>
                    {
                        session.Character.Inventory.DeleteById(inv.Id);
                        session.SendPacket(UserInterfaceHelper.Instance.GenerateInventoryRemove(inv.Type, inv.Slot));
                    });
                session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}