////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using System;

namespace OpenNos.Handler.CommandPackets.Inventory
{
    [PacketHeader("$CloneItem", PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class CloneItemPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public byte Slot { get; set; }

        public InventoryType Type { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 3)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                CloneItemPacket packetDefinition = new CloneItemPacket();
                if (byte.TryParse(packetSplit[2], out byte slot) && Enum.TryParse(packetSplit[3], out InventoryType type))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.Slot = slot;
                    packetDefinition.Type = type;
                }
                packetDefinition.ExecuteHandler(sess);
                LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(CloneItemPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Clone SLOT INVENTORYTYPE";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), $"[Clone]Slot: {Slot}");
                ItemInstance item =
                    session.Character.Inventory.LoadBySlotAndType(Slot, Type);
                if (item != null)
                {
                    item = item.DeepCopy();
                    item.Id = Guid.NewGuid();
                    session.Character.Inventory.AddToInventory(item);
                }
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}