////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;

namespace OpenNos.Handler.CommandPackets.Character
{
    [PacketHeader("$ArenaWinner", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ArenaWinnerPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            ArenaWinnerPacket packetDefinition = new ArenaWinnerPacket();
            packetDefinition.ExecuteHandler(session as ClientSession);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(ArenaWinnerPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$ArenaWinner";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[ArenaWinner]");

            session.Character.ArenaWinner = session.Character.ArenaWinner == 0 ? 1 : 0;
            session.CurrentMapInstance?.Broadcast(session.Character.GenerateCMode());
            session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
        }

        #endregion
    }
}