////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;

namespace OpenNos.Handler.CommandPackets.Character
{
    [PacketHeader("$BlockPM", PassNonParseablePacket = true, Authority = AuthorityType.TGM)]
    public class BlockPMPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            BlockPMPacket packetDefinition = new BlockPMPacket();
            packetDefinition.ExecuteHandler(session as ClientSession, packet);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(BlockPMPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$BlockPM";

        private void ExecuteHandler(ClientSession session, string packet)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[BlockPM]");
            LogHelper.Instance.InsertCommandLog(session.Character.CharacterId, packet, session.IpAddress);

            if (!session.Character.GmPvtBlock)
            {
                session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("GM_BLOCK_ENABLE"),
                    10));
                session.Character.GmPvtBlock = true;
            }
            else
            {
                session.SendPacket(
                    session.Character.GenerateSay(Language.Instance.GetMessageFromKey("GM_BLOCK_DISABLE"), 10));
                session.Character.GmPvtBlock = false;
            }
        }

        #endregion
    }
}