////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.DAL;
using OpenNos.Data;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using OpenNos.GameObject.Networking;
using System;
using System.Linq;

namespace OpenNos.Handler.CommandPackets.Character
{
    [PacketHeader("$BlockExp", PassNonParseablePacket = true, Authority = AuthorityType.SGM)]
    public class BlockExpPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public string CharacterName { get; set; }

        public int Duration { get; set; }

        public string Reason { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            string[] packetSplit = packet.Split(new[] { ' ' }, 5);
            if (!(session is ClientSession sess))
            {
                return;
            }
            if (packetSplit.Length < 4)
            {
                sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                return;
            }
            BlockExpPacket packetDefinition = new BlockExpPacket();
            if (!string.IsNullOrEmpty(packetSplit[2])
                && int.TryParse(packetSplit[3], out int duration))
            {
                packetDefinition._isParsed = true;
                packetDefinition.CharacterName = packetSplit[2];
                packetDefinition.Duration = duration;
                packetDefinition.Reason = string.IsNullOrEmpty(packetSplit[4]) ? string.Empty : packetSplit[4].Trim();
            }
            packetDefinition.ExecuteHandler(sess);
            LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(BlockExpPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$BlockExp CHARACTERNAME DURATION REASON";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[BlockExp]CharacterName: {CharacterName} Reason: {Reason} Until: {DateTime.UtcNow.AddMinutes(Duration)}");

                if (Duration == 0)
                {
                    Duration = 60;
                }
                CharacterDTO character = DAOFactory.CharacterDAO.LoadByName(CharacterName);
                if (character != null)
                {
                    ClientSession targetSession =
                        ServerManager.Instance.Sessions.FirstOrDefault(s =>
                            s.Character?.Name == CharacterName);
                    targetSession?.SendPacket(Duration == 1
                        ? UserInterfaceHelper.GenerateInfo(
                            string.Format(Language.Instance.GetMessageFromKey("MUTED_SINGULAR"), Reason))
                        : UserInterfaceHelper.GenerateInfo(string.Format(
                            Language.Instance.GetMessageFromKey("MUTED_PLURAL"), Reason,
                            Duration)));
                    PenaltyLogDTO log = new PenaltyLogDTO
                    {
                        AccountId = character.AccountId,
                        Reason = Reason,
                        Penalty = PenaltyType.BlockExp,
                        DateStart = DateTime.UtcNow,
                        DateEnd = DateTime.UtcNow.AddMinutes(Duration),
                        AdminName = targetSession?.Character.Name
                    };
                    GameObject.Character.InsertOrUpdatePenalty(log);
                    session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
                }
                else
                {
                    session.SendPacket(
                        session.Character.GenerateSay(Language.Instance.GetMessageFromKey("USER_NOT_FOUND"), 10));
                }
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}