////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Buff", PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class BuffPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public short CardId { get; set; }

        public byte? Level { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            string[] packetSplit = packet.Split(' ');
            if (!(session is ClientSession sess))
            {
                return;
            }

            if (packetSplit.Length < 3)
            {
                sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                return;
            }

            BuffPacket packetDefinition = new BuffPacket();
            if (short.TryParse(packetSplit[2], out short cardId))
            {
                packetDefinition._isParsed = true;
                packetDefinition.CardId = cardId;
                packetDefinition.Level = packetSplit.Length >= 4
                                         && byte.TryParse(packetSplit[3], out byte level)
                    ? level
                    : (byte?)null;
            }

            packetDefinition.ExecuteHandler(sess);
            LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(BuffPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Buff CARDID LEVEL(?)";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Buff buff = new Buff(CardId, Level ?? 1);
                session.Character.AddBuff(buff, session.Character.BattleEntity);
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}