////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;

namespace OpenNos.Handler.CommandPackets.Character
{
    [PacketHeader("$ChangeSex", "$Sex" , PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class ChangeSexPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            ChangeSexPacket packetDefinition = new ChangeSexPacket();
            packetDefinition.ExecuteHandler(session as ClientSession);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(ChangeSexPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$ChangeSex";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[ChangeSex]");
            session.Character.ChangeSex();
        }

        #endregion
    }
}