////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.DAL;
using OpenNos.Data;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Networking;
using OpenNos.Handler.Extensions;

namespace OpenNos.Handler.CommandPackets.Character
{
    [PacketHeader("$CharStat", PassNonParseablePacket = true, Authority = AuthorityType.SGM)]
    public class CharacterStatsPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public string CharacterName { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            string[] packetSplit = packet.Split(' ');
            if (!(session is ClientSession sess))
            {
                return;
            }

            if (packetSplit.Length < 3)
            {
                sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                return;
            }

            CharacterStatsPacket packetDefinition = new CharacterStatsPacket();
            if (!string.IsNullOrEmpty(packetSplit[2]))
            {
                packetDefinition._isParsed = true;
                packetDefinition.CharacterName = packetSplit[2];
            }

            packetDefinition.ExecuteHandler(sess);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(CharacterStatsPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$CharStat CHARACTERNAME";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[CharStat]CharacterName: {CharacterName}");

                if (ServerManager.Instance.GetSessionByCharacterName(CharacterName) != null)
                {
                    GameObject.Character character = ServerManager.Instance.GetSessionByCharacterName(CharacterName).Character;
                    session.SendStats(character);
                }
                else if (DAOFactory.CharacterDAO.LoadByName(CharacterName) != null)
                {
                    CharacterDTO characterDto = DAOFactory.CharacterDAO.LoadByName(CharacterName);
                    session.SendStats(characterDto);
                }
                else
                {
                    session.SendPacket(
                        session.Character.GenerateSay(Language.Instance.GetMessageFromKey("USER_NOT_FOUND"), 10));
                }
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}