////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;

namespace OpenNos.Handler.CommandPackets.Character
{
    [PacketHeader("$GodMode", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class GodModePacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                GodModePacket packetDefinition = new GodModePacket();
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(GodModePacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$GodMode";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[GodMode]");

            session.Character.HasGodMode = !session.Character.HasGodMode;
            session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
        }

        #endregion
    }
}