////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;

namespace OpenNos.Handler.CommandPackets.Character
{
    [PacketHeader("$Speed", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class SpeedPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public byte Value { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 3)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                SpeedPacket packetDefinition = new SpeedPacket();
                if (byte.TryParse(packetSplit[2], out byte value))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.Value = value;
                }
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(SpeedPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Speed VALUE";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), $"[Speed]Value: {Value}");

                if (Value < 60)
                {
                    session.Character.Speed = Value;
                    session.Character.IsCustomSpeed = true;
                    session.SendPacket(session.Character.GenerateCond());
                }
                if (Value == 0)
                {
                    session.Character.IsCustomSpeed = false;
                    session.Character.LoadSpeed();
                    session.SendPacket(session.Character.GenerateCond());
                }
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}