////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;

namespace OpenNos.Handler.CommandPackets.Character
{
    [PacketHeader("$Undercover", "$UC", PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class UndercoverPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                UndercoverPacket packetDefinition = new UndercoverPacket();
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(UndercoverPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Undercover ";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[Undercover]");

            session.Character.Undercover = !session.Character.Undercover;
            session.SendPacket(session.Character.GenerateEq());
            session.CurrentMapInstance?.Broadcast(session, session.Character.GenerateIn(), ReceiverType.AllExceptMe);
            session.CurrentMapInstance?.Broadcast(session, session.Character.GenerateGidx(), ReceiverType.AllExceptMe);
        }

        #endregion
    }
}