////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using OpenNos.GameObject.Networking;
using System;
using System.Threading.Tasks;

namespace OpenNos.Handler.CommandPackets.Act4
{
    [PacketHeader("$Act4Stat", Authority = AuthorityType.SGM)]
    public class Act4StatPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public FactionType Faction { get; set; }

        public int Value { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            string[] packetSplit = packet.Split(' ');
            if (!(session is ClientSession sess))
            {
                return;
            }
            if (packetSplit.Length < 4)
            {
                sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                return;
            }
            Act4StatPacket packetDefinition = new Act4StatPacket();
            if (Enum.TryParse(packetSplit[2], out FactionType faction) && int.TryParse(packetSplit[3], out int value))
            {
                packetDefinition._isParsed = true;
                packetDefinition.Faction = faction;
                packetDefinition.Value = value;
            }
            packetDefinition.ExecuteHandler(sess);
            LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(Act4StatPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Act4Stat FACTION VALUE";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed && ServerManager.Instance.ChannelId == 51)
            {
                switch (Faction)
                {
                    case FactionType.Angel:
                        ServerManager.Instance.Act4AngelStat.Percentage = Value;
                        break;

                    case FactionType.Demon:
                        ServerManager.Instance.Act4DemonStat.Percentage = Value;
                        break;
                }
                Parallel.ForEach(ServerManager.Instance.Sessions, sess => sess.SendPacket(sess.Character.GenerateFc()));
                session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}