////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using System.Linq;
using System.Threading.Tasks;

namespace OpenNos.Handler.CommandPackets.Map
{
    [PacketHeader("$ClearMap", PassNonParseablePacket = true, Authority =AuthorityType.SGM)]
    public class ClearMapPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 2)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }

                ClearMapPacket packetDefinition = new ClearMapPacket();
                if (true /*parsing here*/)
                {
                    packetDefinition._isParsed = true;

                    // Set Packet Properties after parsing
                }

                packetDefinition.ExecuteHandler(sess);
                LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(ClearMapPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$ClearMap";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[ClearMap]MapId: {session.CurrentMapInstance.MapInstanceId}");

                Parallel.ForEach(session.CurrentMapInstance.Monsters.Where(s => s.ShouldRespawn != true), monster =>
                {
                    session.CurrentMapInstance.Broadcast(StaticPacketHelper.Out(UserType.Monster,
                        monster.MapMonsterId));
                    session.CurrentMapInstance.RemoveMonster(monster);
                });
                Parallel.ForEach(session.CurrentMapInstance.DroppedList.GetAllItems(), drop =>
                {
                    session.CurrentMapInstance.Broadcast(StaticPacketHelper.Out(UserType.Object, drop.TransportId));
                    session.CurrentMapInstance.DroppedList.Remove(drop.TransportId);
                });
                session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}