////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;

namespace OpenNos.Handler.CommandPackets.Map
{
    [PacketHeader("$MapDance", PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class MapDancePacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                MapDancePacket packetDefinition = new MapDancePacket();
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(MapDancePacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$MapDance ";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[MapDance]");

            if (session.HasCurrentMapInstance)
            {
                session.CurrentMapInstance.IsDancing = !session.CurrentMapInstance.IsDancing;
                if (session.CurrentMapInstance.IsDancing)
                {
                    session.Character.Dance();
                    session.CurrentMapInstance?.Broadcast("dance 2");
                }
                else
                {
                    session.Character.Dance();
                    session.CurrentMapInstance?.Broadcast("dance");
                }

                session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
            }
        }

        #endregion
    }
}