////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;

namespace OpenNos.Handler.CommandPackets.Map
{
    [PacketHeader("$MapPVP" , PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class MapPvpPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                MapPvpPacket packetDefinition = new MapPvpPacket();
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(MapPvpPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$MapPVP ";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[MapPVP]");

            session.CurrentMapInstance.IsPvp = !session.CurrentMapInstance.IsPvp;
            session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
        }

        #endregion
    }
}