////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.DAL;
using OpenNos.Data;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Networking;
using System.Linq;

namespace OpenNos.Handler.CommandPackets.Map
{
    [PacketHeader("$MapStat", PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class MapStatisticsPacket
    {
        #region Properties

        public short? MapId { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                MapStatisticsPacket packetDefinition = new MapStatisticsPacket
                {
                    MapId = packetSplit.Length >= 3 && short.TryParse(packetSplit[2], out short mapId) ? mapId : (short?)null
                };
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(MapStatisticsPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$MapStat MAPID(?)";

        private void ExecuteHandler(ClientSession session)
        {
            void SendMapStats(MapDTO map, MapInstance mapInstance)
            {
                if (map != null && mapInstance != null)
                {
                    session.SendPacket(session.Character.GenerateSay("-------------MapData-------------", 10));
                    session.SendPacket(session.Character.GenerateSay(
                        $"MapId: {map.MapId}\n" +
                        $"MapMusic: {map.Music}\n" +
                        $"MapName: {map.Name}\n" +
                        $"MapShopAllowed: {map.ShopAllowed}", 10));
                    session.SendPacket(session.Character.GenerateSay("---------------------------------", 10));
                    session.SendPacket(session.Character.GenerateSay("---------MapInstanceData---------", 10));
                    session.SendPacket(session.Character.GenerateSay(
                        $"MapInstanceId: {mapInstance.MapInstanceId}\n" +
                        $"MapInstanceType: {mapInstance.MapInstanceType}\n" +
                        $"MapMonsterCount: {mapInstance.Monsters.Count}\n" +
                        $"MapNpcCount: {mapInstance.Npcs.Count}\n" +
                        $"MapPortalsCount: {mapInstance.Portals.Count}\n" +
                        $"MapInstanceUserShopCount: {mapInstance.UserShops.Count}\n" +
                        $"SessionCount: {mapInstance.Sessions.Count()}\n" +
                        $"MapInstanceXpRate: {mapInstance.XpRate}\n" +
                        $"MapInstanceDropRate: {mapInstance.DropRate}\n" +
                        $"MapInstanceMusic: {mapInstance.InstanceMusic}\n" +
                        $"ShopsAllowed: {mapInstance.ShopAllowed}\n" +
                        $"DropAllowed: {mapInstance.DropAllowed}\n" +
                        $"IsPVP: {mapInstance.IsPvp}\n" +
                        $"IsSleeping: {mapInstance.IsSleeping}\n" +
                        $"Dance: {mapInstance.IsDancing}", 10));
                    session.SendPacket(session.Character.GenerateSay("---------------------------------", 10));
                }
            }

            if (MapId.HasValue)
            {
                MapDTO map = DAOFactory.MapDAO.LoadById(MapId.Value);
                MapInstance mapInstance = ServerManager.GetMapInstanceByMapId(MapId.Value);
                if (map != null && mapInstance != null)
                {
                    SendMapStats(map, mapInstance);
                }
            }
            else if (session.HasCurrentMapInstance)
            {
                MapDTO map = DAOFactory.MapDAO.LoadById(session.CurrentMapInstance.Map.MapId);
                if (map != null)
                {
                    SendMapStats(map, session.CurrentMapInstance);
                }
            }
        }

        #endregion
    }
}