////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("c_close")]
    public class CClosePacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}