////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using GloomyTale.Core;

namespace GloomyTale.GameObject.Packets.ClientPackets
{
    [PacketHeader("glrm")]
    public class FamilyDismissPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}