////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("frank_cts")]
    public class FrankCtsPacket : PacketDefinition
    {
        #region Properties        

        [PacketIndex(0)]
        public byte Type { get; set; }

        #endregion
    }
}