////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("mledit")]
    public class MLEditPacket : PacketDefinition
    {
        #region Properties
        [PacketIndex(0)]
        public byte Type { get; set; }
        [PacketIndex(1,SerializeToEnd = true)]
        public string Parameters { get; set; }
        #endregion
    }
}