////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("npinfo")]
    public class NpinfoPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Page { get; set; }

        #endregion
    }
}