////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("preq")]
    public class PreqPacket : PacketDefinition
    {
        #region Properties
        
        [PacketIndex(0)]
        public short? Parameter { get; set; }
        
        #endregion
    }
}