////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("pulse")]
    public class PulsePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int Tick { get; set; }
      
        #endregion
    }
}