////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("rstart")]
    public class RStartPacket : PacketDefinition
    {
        #region Properties        

        [PacketIndex(0)]
        public byte? Type { get; set; }
        
        #endregion
    }
}