////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("say_p")]
    public class SayPPacket : PacketDefinition
    {
        #region Properties
        [PacketIndex(0)]
        public int PetId { get; set; }

        [PacketIndex(1, SerializeToEnd = true)]
        public string Message { get; set; }

        #endregion
    }
}