////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;

namespace GloomyTale.GameObject
{
    [PacketHeader("sortopen")]
    public class SortOpenPacket : PacketDefinition
    {
    }
}