////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("eq")]
    public class EqPacket
    {
        [PacketIndex(0)]
        public long Id { get; set; }
    }

    [PacketHeader("eqsub")]
    public class EqSubPacket
    {
    }

    [PacketHeader("eqraresub")]
    public class EqRareSubPacket
    {
    }
}
