// <auto-generated />
namespace OpenNos.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview9-19423-04")]
    public sealed partial class Antares10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Antares10));
        
        string IMigrationMetadata.Id
        {
            get { return "201911181757043_Antares10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
