// <auto-generated />
namespace OpenNos.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview9-19423-04")]
    public sealed partial class Antares12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Antares12));
        
        string IMigrationMetadata.Id
        {
            get { return "201912211129033_Antares12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
