////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject
{
    [PacketHeader("b_i")]
    public class BIPacket
    {
        #region Properties

        public InventoryType InventoryType { get; set; }

        public byte Slot { get; set; }

        public byte? Option { get; set; }

        #endregion
    }
}
