////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("preq")]
    public class PreqPacket
    {
        #region Properties
        
        [PacketIndex(0)]
        public short? Parameter { get; set; }
        
        #endregion
    }
}