////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("ob_a")]
    public class UseIconFalconSkillPacket
    {
        #region Properties        
        
        #endregion
    }
}