////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;

namespace OpenNos.Handler.CommandPackets.AddEntities
{
    [PacketHeader("$AddSkill", PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class AddSkillPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public short SkillVnum { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            string[] packetSplit = packet.Split(' ');
            if (!(session is ClientSession sess))
            {
                return;
            }
            if (packetSplit.Length < 3)
            {
                sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                return;
            }
            AddSkillPacket packetDefinition = new AddSkillPacket();
            if (short.TryParse(packetSplit[2], out short skillVNum))
            {
                packetDefinition._isParsed = true;
                packetDefinition.SkillVnum = skillVNum;
            }
            packetDefinition.ExecuteHandler(sess);
            LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(AddSkillPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$AddSkill SKILLVNUM";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[AddSkill]SkillVNum: {SkillVnum}");
                session.Character.AddSkill(SkillVnum);
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}