////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Networking;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$ChannelInfo", PassNonParseablePacket = true, Authority = AuthorityType.SGM)]
    public class ChannelInfoPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            ChannelInfoPacket packetDefinition = new ChannelInfoPacket();
            packetDefinition.ExecuteHandler(session as ClientSession);
        }

        public static void Register() => PacketFacility.AddHandler(typeof(ChannelInfoPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$ChannelInfo";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[ChannelInfo]");

            session.SendPacket(session.Character.GenerateSay(
                $"-----------Channel Info-----------\n-------------Channel:{ServerManager.Instance.ChannelId}-------------",
                11));
            foreach (ClientSession targetSession in ServerManager.Instance.Sessions)
            {
                session.SendPacket(
                    session.Character.GenerateSay(
                        $"CharacterName: {targetSession.Character.Name} SessionId: {targetSession.SessionId}", 12));
            }

            session.SendPacket(session.Character.GenerateSay("----------------------------------------", 11));
        }

        #endregion
    }
}