////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Effect", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class EffectCommandPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public int EffectId { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 3)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                EffectCommandPacket packetDefinition = new EffectCommandPacket();
                if (int.TryParse(packetSplit[2], out int id))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.EffectId = id;
                }
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(EffectCommandPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Effect EFFECTID";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[Effect]EffectId: {EffectId}");

                session.CurrentMapInstance?.Broadcast(
                    StaticPacketHelper.GenerateEff(UserType.Player, session.Character.CharacterId,
                        EffectId), session.Character.PositionX, session.Character.PositionY);
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}