////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using OpenNos.GameObject.Networking;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Faction", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class FactionPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                FactionPacket packetDefinition = new FactionPacket();
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(FactionPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Faction";

        private void ExecuteHandler(ClientSession Session)
        {
            if (ServerManager.Instance.ChannelId == 51)
            {
                Session.SendPacket(
                    UserInterfaceHelper.GenerateMsg(Language.Instance.GetMessageFromKey("CHANGE_NOT_PERMITTED_ACT4"),
                        0));
                return;
            }
            if (Session.CurrentMapInstance.MapInstanceType == MapInstanceType.Act4ShipAngel
                || Session.CurrentMapInstance.MapInstanceType == MapInstanceType.Act4ShipDemon)
            {
                Session.SendPacket(
                    UserInterfaceHelper.GenerateMsg(Language.Instance.GetMessageFromKey("CHANGE_NOT_PERMITTED_ACT4SHIP"),
                        0));
                return;
            }
            Session.SendPacket("scr 0 0 0 0 0 0 0");
            if (Session.Character.Faction == FactionType.Angel)
            {
                Session.Character.Faction = FactionType.Demon;
                Session.SendPacket(
                    UserInterfaceHelper.GenerateMsg(Language.Instance.GetMessageFromKey($"GET_PROTECTION_POWER_2"),
                        0));
            }
            else
            {
                Session.Character.Faction = FactionType.Angel;
                Session.SendPacket(
                    UserInterfaceHelper.GenerateMsg(Language.Instance.GetMessageFromKey($"GET_PROTECTION_POWER_1"),
                        0));
            }
            Session.SendPacket(StaticPacketHelper.GenerateEff(UserType.Player,
                Session.Character.CharacterId, 4799 + (byte)Session.Character.Faction));
            Session.SendPacket(Session.Character.GenerateFaction());
            if (ServerManager.Instance.ChannelId == 51)
            {
                Session.SendPacket(Session.Character.GenerateFc());
            }
        }

        #endregion
    }
}