////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using System;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$HairStyle", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class HairStylePacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public HairStyleType HairStyle { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 3)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                HairStylePacket packetDefinition = new HairStylePacket();
                if (Enum.TryParse(packetSplit[2], out HairStyleType type))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.HairStyle = type;
                }
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(HairStylePacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$HairStyle COLORID";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[HairStyle]HairStyle: {HairStyle}");

                session.Character.HairStyle = HairStyle;
                session.SendPacket(session.Character.GenerateEq());
                session.CurrentMapInstance?.Broadcast(session.Character.GenerateIn());
                session.CurrentMapInstance?.Broadcast(session.Character.GenerateGidx());
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}