////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Networking;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Home", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class HomePacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                HomePacket packetDefinition = new HomePacket();
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(HomePacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Home";

        private void ExecuteHandler(ClientSession Session)
        {
            if (Session.Character.Channel.ChannelId != 51)
            {
                Logger.LogUserEvent("GMCOMMAND", Session.GenerateIdentity(), $"[Home]");
                ServerManager.Instance.ChangeMap(Session.Character.CharacterId, 129, 127, 73);
            }
            else
            {
                Session.SendPacket(Session.Character.GenerateSay(Language.Instance.GetMessageFromKey("You can't do it if you are in act4."), 10));
            }
        }

        #endregion
    }
}