////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.DAL;
using OpenNos.Data;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using OpenNos.GameObject.Networking;
using OpenNos.Master.Library.Client;
using System.Threading.Tasks;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$KickSession", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class KickSessionPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public string AccountName { get; set; }

        public int? SessionId { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 3)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                KickSessionPacket packetDefinition = new KickSessionPacket();
                if (!string.IsNullOrWhiteSpace(packetSplit[2]) && int.TryParse(packetSplit[3], out int sessionId))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.AccountName = packetSplit[2];
                    packetDefinition.SessionId = sessionId;
                }
                packetDefinition.ExecuteHandler(sess);
                LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(KickSessionPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Kick CHARACTERNAME";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[Kick]AccountName: {AccountName} SessionId: {SessionId}");
                if (SessionId.HasValue) //if you set the sessionId, remove account verification
                {
                    AccountName = "";
                }

                session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
                AccountDTO account = DAOFactory.AccountDAO.LoadByName(AccountName);
                CommunicationServiceClient.Instance.KickSession(account?.AccountId, SessionId);
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}