////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.DAL;
using OpenNos.Data;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using System;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Maintenance", PassNonParseablePacket = true, Authority = AuthorityType.GA)]

    public class MaintenancePacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public int Delay { get; set; }

        public int Duration { get; set; }

        public string Reason { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(new[] { ' ' }, 5);
                if (packetSplit.Length < 5)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }

                MaintenancePacket packetDefinition = new MaintenancePacket();
                if (int.TryParse(packetSplit[2], out int delay) && int.TryParse(packetSplit[3], out int duration)
                    && !string.IsNullOrWhiteSpace(packetSplit[4]))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.Delay = delay;
                    packetDefinition.Duration = duration;
                    packetDefinition.Reason = packetSplit[4];
                }

                packetDefinition.ExecuteHandler(sess);
                LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(MaintenancePacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Maintenance DELAY DURATION REASON";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[Maintenance]Delay: {Delay} Duration: {Duration} Reason: {Reason}");
                DateTime dateStart = DateTime.UtcNow.AddMinutes(Delay);
                MaintenanceLogDTO maintenance = new MaintenanceLogDTO
                {
                    DateEnd = dateStart.AddMinutes(Duration),
                    DateStart = dateStart,
                    Reason = Reason
                };
                DAOFactory.MaintenanceLogDAO.Insert(maintenance);
                session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("DONE"), 10));
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}
