////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using OpenNos.Handler.Extensions;
using System;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Mute", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class MutePacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public string CharacterName { get; set; }

        public int Duration { get; set; }

        public string Reason { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(new[] { ' ' }, 5);
                if (packetSplit.Length < 5)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }

                MutePacket packetDefinition = new MutePacket();
                if (!string.IsNullOrWhiteSpace(packetSplit[2]) && int.TryParse(packetSplit[3], out int duration)
                    && !string.IsNullOrWhiteSpace(packetSplit[4]))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.CharacterName = packetSplit[2];
                    packetDefinition.Duration = duration;
                    packetDefinition.Reason = packetSplit[4];
                }

                packetDefinition.ExecuteHandler(sess);
                LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(MutePacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Mute NAME TIME(MINUTES) REASON";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[Mute]CharacterName: {CharacterName} Reason: {Reason} Until: {DateTime.UtcNow.AddMinutes(Duration)}");

                Reason = Reason.Trim();
                session.MuteMethod(CharacterName, Reason, Duration);
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}