////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Position", PassNonParseablePacket = true, Authority =AuthorityType.GM)]
    public class PositionPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                PositionPacket packetDefinition = new PositionPacket();
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(PositionPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Position ";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[Position]");

            session.SendPacket(session.Character.GenerateSay(
                $"Map:{session.Character.MapInstance.Map.MapId} - X:{session.Character.PositionX} - Y:{session.Character.PositionY} - Dir:{session.Character.Direction} - Cell:{session.CurrentMapInstance.Map.JaggedGrid[session.Character.PositionX][session.Character.PositionY]?.Value}",
                12));
        }

        #endregion
    }
}