////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;
using System;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Rarify", PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class RarifyPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public RarifyMode Mode { get; set; }

        public RarifyProtection Protection { get; set; }

        public short Slot { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 5)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                RarifyPacket packetDefinition = new RarifyPacket();
                if (short.TryParse(packetSplit[2], out short slot) && Enum.TryParse(packetSplit[3], out RarifyMode mode) && Enum.TryParse(packetSplit[4], out RarifyProtection protection))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.Slot = slot;
                    packetDefinition.Mode = mode;
                    packetDefinition.Protection = protection;
                }
                packetDefinition.ExecuteHandler(sess);
                LogHelper.Instance.InsertCommandLog(sess.Character.CharacterId, packet, sess.IpAddress);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(RarifyPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Rarify SLOT MODE PROTECTION";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[Rarify]Slot: {Slot} Mode: {Mode} Protection: {Protection}");

                if (Slot >= 0)
                {
                    ItemInstance wearableInstance = session.Character.Inventory.LoadBySlotAndType(Slot, 0);
                    wearableInstance?.RarifyItem(session, Mode, Protection);
                }
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}