////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.DAL;
using OpenNos.Data;
using OpenNos.Data.I18N;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Networking;
using System.Linq;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$SearchMonster", "$SMonster", PassNonParseablePacket = true, Authority = AuthorityType.SGM)]
    public class SearchMonsterPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public string Name { get; set; }

        public byte Page { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(new[] { ' ' }, 3);
                if (packetSplit.Length < 3)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                SearchMonsterPacket packetDefinition = new SearchMonsterPacket();
                if (!string.IsNullOrWhiteSpace(packetSplit[2]))
                {
                    packetDefinition._isParsed = true;
                    string[] searchSplit = packetSplit[2].Split(' ');
                    packetDefinition.Page =
                        byte.TryParse(searchSplit[searchSplit.Length - 1], out byte pg) ? pg : (byte)0;
                    packetDefinition.Name = searchSplit[searchSplit.Length - 1] != packetDefinition.Page.ToString()
                        ? packetSplit[2]
                        : string.Join(" ", searchSplit.Take(searchSplit.Length - 1));
                }
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(SearchMonsterPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$SearchMonster NAME PAGE(?)";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[SearchMonster]Name: {Name} Page: {Page}");

                foreach (II18NNpcMonsterDto i18nItemName in DAOFactory.I18NNpcMonsterDAO.FindByName(Name, session.Account.Language).OrderBy(s => s.Key).Skip(Page * 200).Take(200).ToList())
                {
                    NpcMonsterDTO npcMonsters = DAOFactory.NpcMonsterDAO.LoadByKey(i18nItemName.Key);
                    if (npcMonsters != null)
                    {
                        NpcMonster npcMonster = ServerManager.GetNpcMonster(npcMonsters.NpcMonsterVNum);
                        if (npcMonster != null)
                        {
                            session.SendPacket(session.Character.GenerateSay(
                            $"[SearchMonster:{Page}]Monster: {(string.IsNullOrEmpty(npcMonster.Name[session.Account.Language]) ? "none" : npcMonster.Name[session.Account.Language])} VNum: {npcMonster.NpcMonsterVNum}",
                            12));
                        }
                        else
                        {
                            session.SendPacket(
                                session.Character.GenerateSay(Language.Instance.GetMessageFromKey("MONSTER_NOT_FOUND"), 11));
                        }
                    }
                }
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}