////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using System;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Sort", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class SortPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public InventoryType InventoryType { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 3)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                SortPacket packetDefinition = new SortPacket();
                if (Enum.TryParse(packetSplit[2], out InventoryType type))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.InventoryType = type;
                }
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(SortPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Sort INVENTORYTYPE";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("USERCOMMAND", session.GenerateIdentity(),
                    $"[Sort]InventoryType: {InventoryType}");
                if (InventoryType == InventoryType.Equipment || InventoryType == InventoryType.Etc || InventoryType == InventoryType.Main)
                {
                    session.Character.Inventory.Reorder(session, InventoryType);
                }
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}