////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Helpers;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$SPRefill", PassNonParseablePacket = true, Authority = AuthorityType.SGM)]
    public class SPRefillPacket
    {
        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                SPRefillPacket packetDefinition = new SPRefillPacket();
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(SPRefillPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$SPRefill ";

        private void ExecuteHandler(ClientSession session)
        {
            Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(), "[SPRefill]");

            session.Character.SpPoint = 10000;
            session.Character.SpAdditionPoint = 1000000;
            session.SendPacket(UserInterfaceHelper.GenerateMsg(Language.Instance.GetMessageFromKey("SP_REFILL"), 0));
            session.SendPacket(session.Character.GenerateSpPoint());
        }

        #endregion
    }
}