////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;
using OpenNos.GameObject;
using OpenNos.GameObject.Packets.ClientPackets;
using System;

namespace OpenNos.Handler.CommandPackets
{
    [PacketHeader("$Upgrade", PassNonParseablePacket = true, Authority = AuthorityType.GA)]
    public class UpgradeCommandPacket
    {
        #region Members

        private bool _isParsed;

        #endregion

        #region Properties

        public UpgradeMode Mode { get; set; }

        public UpgradeProtection Protection { get; set; }

        public short Slot { get; set; }

        #endregion

        #region Methods

        public static void HandlePacket(object session, string packet)
        {
            if (session is ClientSession sess)
            {
                string[] packetSplit = packet.Split(' ');
                if (packetSplit.Length < 5)
                {
                    sess.SendPacket(sess.Character.GenerateSay(ReturnHelp(), 10));
                    return;
                }
                UpgradeCommandPacket packetDefinition = new UpgradeCommandPacket();
                if (short.TryParse(packetSplit[2], out short slot) && Enum.TryParse(packetSplit[3], out UpgradeMode mode) && Enum.TryParse(packetSplit[4], out UpgradeProtection protection))
                {
                    packetDefinition._isParsed = true;
                    packetDefinition.Slot = slot;
                    packetDefinition.Mode = mode;
                    packetDefinition.Protection = protection;
                }
                packetDefinition.ExecuteHandler(sess);
            }
        }

        public static void Register() => PacketFacility.AddHandler(typeof(UpgradeCommandPacket), HandlePacket, ReturnHelp);

        public static string ReturnHelp() => "$Upgrade SLOT MODE PROTECTION";

        private void ExecuteHandler(ClientSession session)
        {
            if (_isParsed)
            {
                Logger.LogUserEvent("GMCOMMAND", session.GenerateIdentity(),
                    $"[Upgrade]Slot: {Slot} Mode: {Mode} Protection: {Protection}");

                if (Slot >= 0)
                {
                    ItemInstance wearableInstance =
                        session.Character.Inventory.LoadBySlotAndType(Slot, 0);
                    wearableInstance?.UpgradeItem(session, Mode, Protection, true);
                }
            }
            else
            {
                session.SendPacket(session.Character.GenerateSay(ReturnHelp(), 10));
            }
        }

        #endregion
    }
}
