////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$Act4Stat", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.GA } )]
    public class Act4StatPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Faction { get; set; }

        [PacketIndex(1)]
        public int Value { get; set; }

        public static string ReturnHelp() => "$Act4Stat <Faction> <Value>";

        #endregion
    }
}