////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$FamilyFaction", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.SGM, AuthorityType.SMOD } )]
    public class FamilyFactionPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string FamilyName { get; set; }

        public static string ReturnHelp() => "$FamilyFaction <Name>";
    }
}