////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$Camouflage" , PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TGM, AuthorityType.TMOD, AuthorityType.GS } )]
    public class InvisiblePacket : PacketDefinition
    {
        public static string ReturnHelp() => "$Camouflage";
    }
}