////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$ResetMap" , PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.GA } )]
    public class MapResetPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$ResetMap";

        #endregion
    }
}