////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$ReloadSI" , PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TM } )]
    public class ReloadSIPacket : PacketDefinition
    {
        #region Properties
        
        public static string ReturnHelp() => "$ReloadSI";

        #endregion
    }
}