////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$ReputationRate", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.GA })]
    public class ReputationRatePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int Value { get; set; }

        public static string ReturnHelp() => "$ReputationRate <Value>";

        #endregion
    }
}