////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$Restart", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TM } )]
    public class RestartPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int Time { get; set; }

        public static string ReturnHelp() => "$Restart <?Delay>";
    }
}