////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$ShutdownAll", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TM } )]
    public class ShutdownAllPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string WorldGroup { get; set; }

        public static string ReturnHelp() => "$ShutdownAll <WorldGroup|*>";
    }
}