////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$Sort", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TGM, AuthorityType.TMOD } )]
    public class SortPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public InventoryType? InventoryType { get; set; }

        public static string ReturnHelp() => "$Sort <InventoryType>";

        #endregion
    }
}