////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using GloomyTale.Core;
using GloomyTale.Domain;

namespace GloomyTale.GameObject.CommandPackets
{
    [PacketHeader("$WigColor", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TGM, AuthorityType.TMOD } )]
    public class WigColorPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Color { get; set; }

        public static string ReturnHelp() => "$WigColor <Value>";

        #endregion
    }
}