////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Act4", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class Act4Packet
    {
        #region Properties
        
        public static string ReturnHelp() => "$Act4";

        #endregion
    }
}