////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$ChangeDignity", "$Dignity" , PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TGM, AuthorityType.TMOD } )]
    public class ChangeDignityPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public float Dignity { get; set; }

        public static string ReturnHelp() => "$ChangeDignity | $Dignity <Value>";

        #endregion
    }
}