////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$CreateItem", "$Item", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.GA } )]
    public class CreateItemPacket
    {
        #region Properties

        [PacketIndex(0)]
        public short VNum { get; set; }

        [PacketIndex(1)]
        public short? Design { get; set; }

        [PacketIndex(2)]
        public byte? Upgrade { get; set; }

        public static string ReturnHelp() => "$CreateItem <VNum> <Design|Rare|Amount|Wings> <Upgrade>";

        #endregion

    }
}