////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$LeaveAct4", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TGM, AuthorityType.TMOD } )]
    public class LeaveAct4Packet : PacketDefinition
    {
        #region Properties
        
        public static string ReturnHelp() => "$LeaveAct4";

        #endregion
    }
}