////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$ReloadSI" , PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TM } )]
    public class ReloadSIPacket : PacketDefinition
    {
        #region Properties
        
        public static string ReturnHelp() => "$ReloadSI";

        #endregion
    }
}